### ISSUE TITLE
"Something went wrong" error when trying to buy album

### ISSUE THREAD

**Issue by Coehill** [funmusicplace/mirlo#787]
I tapped the "buy" button from firefox mobile on Android version 14 on the page below and I got a "Something went wrong" error popup.
https://mirlo.space/bgm/release/your-life

Unfortunately, this was on mobile so I haven't had a chance to try to reproduce it on a desktop with dev tools.

Is this reproducible by anybody else?

![c731c8dd-ca6e-4fe9-8e35-bb598207bd43](https://github.com/funmusicplace/mirlo/assets/13023025/3203e8e3-8cd1-4169-80c1-bc8e5df4e06b)

**Comment by simonv3** [comment]
Try now? 

Stripe was complaining that the product didn't exist for the artist, which I'm going to guess is due to the artist changing which stripe account they use, which we don't properly reset product keys. I think I've patched this by setting the product key on album 873 to null but we should make it so that after connecting stripe we reset stripeKeys for all artists things.

* [ ] trackGroup
* [ ] Subscription

**Comment by Coehill** [comment]
Thank you! This has been resolved.

**Comment by simonv3** [comment]
Re-opening because the problem is still there structurally, still need to implement it so that it doesn't happen for others.

**Comment by CPacaud123** [comment]
I am getting this same error today trying to get a free download link for an album: https://mirlo.space/nicolas-hussein/release/orchestrations

I tried the artist's other albums and I am getting the same error as well.

![image](https://github.com/user-attachments/assets/a35e7fad-3ef4-46c6-9705-8639d1917a48)

**Comment by simonv3** [comment]
We handled this by if the product doesn't exist in stripe, fail properly, and then create a new product.
